### ISSUE TITLE
IdleManager support for Yahoo! mail folders

### ISSUE THREAD

**Issue by dmoore2068** [eclipse-ee4j/mail#419]
I am attempting to use JavaMail to connect to my Yahoo! email inbox and listen for new messages. However, using either IMAPFolder.idle() or the IdleManager class, I get the following error: 

```
javax.mail.MessagingException: IDLE not supported;
  nested exception is:
	com.sun.mail.iap.BadCommandException: IDLE not supported
	at com.sun.mail.imap.IMAPFolder.doOptionalCommand(IMAPFolder.java:3878)
	at com.sun.mail.imap.IMAPFolder.startIdle(IMAPFolder.java:3199)
	at com.sun.mail.imap.IdleManager.watch(IdleManager.java:217)
	at daytrading.services.EmailService.watch(EmailService.java:130)
	at daytrading.services.EmailService.startService(EmailService.java:111)
	at daytrading.Main.main(Main.java:89)
Caused by: com.sun.mail.iap.BadCommandException: IDLE not supported
	at com.sun.mail.imap.protocol.IMAPProtocol.idleStart(IMAPProtocol.java:3154)
	at com.sun.mail.imap.IMAPFolder$19.doCommand(IMAPFolder.java:3210)
	at com.sun.mail.imap.IMAPFolder.doProtocolCommand(IMAPFolder.java:3912)
	at com.sun.mail.imap.IMAPFolder.doOptionalCommand(IMAPFolder.java:3876)
	... 5 more```

Is there any workaround in place for the Folder idle() or IdleManager watch() commands to work with Yahoo! mail folders?

**Comment by bshannon** [comment]
The server doesn't appear to support the IDLE command.  It's an optional IMAP extension
so there's not much JavaMail can do about it.  Use a better server.  The only workaround
is for your application to just poll the server periodically by using Folder.getMessageCount().
