### ISSUE TITLE
MimeBodyPart.setDataHandler(jakarta.activation.DataHandler)

### ISSUE THREAD

**Issue by gregh3269** [eclipse-ee4j/mail#488]
I have upgraded to 2.0 and the instructions state all I need to do is change all imports that use javax.mail.* to instead use jakarta.mail.*.

My app now won't compile due to jakarta.activation.DataHandler  and  javax.activation.DataHandler incompatibility.

jakarta.mail.internet.MimeBodyPart

```java
MimeBodyPart resource = new MimeBodyPart();
resource.setDataHandler(
	new javax.activation.DataHandler(
			source) {
		public String getContentType() {
			return URLConnection.getFileNameMap()
					.getContentTypeFor(src);
		}
	});
```
Where does jakarta.activation.DataHandler now come from?  I have javax.activation-1.2.0.jar in my class path but I cannot find https://eclipse-ee4j.github.io/jaf/ jars

Cheers

**Comment by mEkdal** [comment]
I have the same/ similar problem.

I changed all references from javax to jakarta and it compiled well.

Execution shows:

The statement: **MimeMessage msg = new MimeMessage(session);** 
causes  **Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/activation/DataHandler**

**Comment by gregh3269** [comment]
There is a jakarta.activation-api-1.2.1.jar but the classes are in /javax/activation/ ??

**Comment by mEkdal** [comment]
Thanks gregh3269 !  :-)

When I added **jakarta.activation-api-2.0.0.jar** in addition to  **jakarta.mail-2.0.0.jar** to the class path it started to work !

**Comment by gregh3269** [comment]
...Guess its something it should mention in the upgrade, as its not obvious.  On https://eclipse-ee4j.github.io/jaf/ there are no hints also.

**Comment by gregh3269** [comment]
Alas, for java 11 it gives

java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:149) ~[jakarta.activation-api-2.0.0.jar:2.0.0]
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:55) ~[jakarta.activation-api-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:127) ~[jakarta.activation-api-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:589) ~[jakarta.activation-api-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289) ~[jakarta.activation-api-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316) ~[jakarta.mail-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551) ~[jakarta.mail-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2237) ~[jakarta.mail-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2197) ~[jakarta.mail-2.0.0.jar:2.0.0]
	at org.events.util.email.MailUtil.sendMessage(MailUtil.java:179) [classes/:?]
	at org.events.util.email.MailUtil.sendTextMessage(MailUtil.java:284) [classes/:?]
	at org.events.util.email.MailUtil.sendSysAdminMail(MailUtil.java:60) [classes/:?]
	at org.events.business.operations.CreateImageOperation.doRun(CreateImageOperation.java:247) [classes/:?]
	at org.events.business.operations.ScheduledOperationImpl.run(ScheduledOperationImpl.java:45) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

Which may be a jdk 11 upgrade issue :-(

**Comment by lukasj** [comment]
`com.sun.mail:jakarta.mail:2.0.0` artifact depends on and requires  `com.sun.activation:jakarta.activation:2.0.0` artifact. Using `jakarta.activation:jakarta.activation-api` is not enough, since that is only API containing no implementation (`com.sun.activation`) classes.

**Comment by imritchie** [comment]
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>2.0.1</version>
</dependency>

<dependency>
    <groupId>com.sun.activation</groupId>
    <artifactId>jakarta.activation</artifactId>
    <version>2.0.1</version>
</dependency>
