### ISSUE TITLE
App crashes on Android 11

### ISSUE THREAD

**Issue by reddigfabian** [eclipse-ee4j/mail#516]
**Describe the bug**
Our app crashes when sending email on Android 11. The same code works on lower versions of Android.

**To Reproduce**
1. Run sample code to send email (SMTP in our case) on Android 10 or lower.
2. Observe email is sent successfully
3. Run sample code to send email (SMTP in our case) on Android 11.
4. Observe the following error message:

```
java.lang.VerifyError: Rejecting class com.sun.mail.handlers.text_plain that attempts to sub-type erroneous class com.sun.mail.handlers.handler_base (declaration of 'com.sun.mail.handlers.text_plain' appears in /data/app/~~3EbawGTZidYfIIoO2umaew==/io.society-2OEoOBxT1vApFcIrsEGFrQ==/base.apk!classes3.dex)
        at java.lang.Class.newInstance(Native Method)
        at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601)
        at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:555)
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:597)
        at javax.activation.DataHandler.writeTo(DataHandler.java:299)
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551)
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2238)
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2198)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1877)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
        at io.society.ui.activity.endpoint.creation.onboarding.viewmodels.OnboardingViewModel$sendEmail$1.invokeSuspend(OnboardingViewModel.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.VerifyError: Verifier rejected class com.sun.mail.handlers.handler_base: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors() failed to verify: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors(): [0x4]  can't resolve returned type 'Unresolved Reference: java.awt.datatransfer.DataFlavor[]' or 'Reference: javax.activation.ActivationDataFlavor[]' (declaration of 'com.sun.mail.handlers.handler_base' appears in /data/app/~~3EbawGTZidYfIIoO2umaew==/io.society-2OEoOBxT1vApFcIrsEGFrQ==/base.apk!classes3.dex)
        at java.lang.Class.newInstance(Native Method) 
        at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601) 
        at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:555) 
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:597) 
        at javax.activation.DataHandler.writeTo(DataHandler.java:299) 
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316) 
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551) 
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2238) 
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2198) 
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1877) 
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300) 
        at io.society.ui.activity.endpoint.creation.onboarding.viewmodels.OnboardingViewModel$sendEmail$1.invokeSuspend(OnboardingViewModel.kt:115) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

**Expected behavior**
Email should send on Android 11 just like it does on lower versions.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11

**Mail server:**
 - Protocol being used: smtp

**Additional context**
This has also been reported on the google issue tracker here: https://issuetracker.google.com/issues/172544275

**Comment by lukasj** [comment]
dup of #489. Can you test with 1.6.6-SNAPSHOT (see https://github.com/eclipse-ee4j/mail/issues/489#issuecomment-765234259), please?
