### ISSUE TITLE
Gmail fails to search for Japanese words.

### ISSUE THREAD

**Issue by hirokatsuhibino** [eclipse-ee4j/mail#526]
If you search for a string containing Japanese characters, the following exception will occur and the search will fail.

version 1.6.2

BX33 SEARCH UNDELETED OR OR OR OR OR FROM "i??i??A￣" TO "i??i??A￣" CC "i??i??A￣" BCC "i??i??A￣" SUBJECT "i??i??A￣" BODY "i??i??A￣" ALL

Caused by: com.sun.mail.iap.BadCommandException: E4 BAD Could not parse command
	at com.sun.mail.iap.Protocol.handleResult(Protocol.java:439)
	at com.sun.mail.imap.protocol.IMAPProtocol.issueSearch(IMAPProtocol.java:2596)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2501)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2486)
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2375)

**Comment by NAVNEETQA** [comment]
Same for me as well .. If anyone knows the answer plz reply on the post
