### ISSUE TITLE
MailHander should catch ServiceConfigurationError

### ISSUE THREAD

**Issue by jmehrens** [eclipse-ee4j/mail#548]
JakaraMail 1.6.6 MailHandler test fails when running under JDK 1.7 with the following:
```
Testcase: testCloseContextClassLoader(com.sun.mail.util.logging.MailHandlerTest):	Caused an ERROR
javax.mail.Provider: Provider com.sun.mail.imap.IMAPProvider not found
java.util.ServiceConfigurationError: javax.mail.Provider: Provider com.sun.mail.imap.IMAPProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at javax.mail.Session.loadProviders(Session.java:964)
	at javax.mail.Session.<init>(Session.java:254)
	at javax.mail.Session.getInstance(Session.java:281)
	at com.sun.mail.util.logging.MailHandler.initSession(MailHandler.java:3448)
	at com.sun.mail.util.logging.MailHandler.writeLogRecords0(MailHandler.java:2823)
	at com.sun.mail.util.logging.MailHandler.writeLogRecords(MailHandler.java:2790)
	at com.sun.mail.util.logging.MailHandler.close(MailHandler.java:853)
	at com.sun.mail.util.logging.MailHandlerTest.testCloseContextClassLoader0(MailHandlerTest.java:2295)
	at com.sun.mail.util.logging.MailHandlerTest.testCloseContextClassLoader(MailHandlerTest.java:2273)
```
1. Install JDK 7.
2. Run the logging-mailhander tests.

In the field, the workaround would be to add a MailHandler.verify property to the logging properties.  The documentation already suggests this.

This appears to be a regression from `GH  323	Support loading protocol providers using ServiceLoader`

The MailHandler should be patched to:

1. Catch ServiceConfigurationError and adapt it so it can be reported to the error manager.
2. The context classloader needs to be adjusted during close and other method to support the service loader.

**Comment by jmehrens** [comment]
@lukasj I think there is potential for a new issue issue here.  At 
https://github.com/eclipse-ee4j/mail/blob/31688b7e1860e83292ec32fb656808447fe13ccb/mail/src/main/java/javax/mail/Session.java#L976

1. Should this use the 2 argument load method and use the given classloader instead of the CCL?  sl = ServiceLoader.load(Provider.class, cl);
2. Should Session try ccl and then fallback to cl?
3. Should session be allowed to throw service configuration error?  It was never added to the JavaDocs and it already has fallback code if service loading fails.  Seems like SCE should be caught and logged for debugging.
